Fix cylps discretize
HERA-Team/pspec_likelihood pull request #59
Opened 2023-06-20 05:59 UTC by steven-murray

Fixes #57

2023-06-20 13:56 UTC, adeliegorce requested changes
All good here, just need to add tests related to that! Thanks

2023-06-20 13:56 UTC, adeliegorce commented on src/pspec_likelihood/likelihood.py
> +        return np.size(self.kpar_bins_obs)
Already fixed in another PR, need to merge

2023-06-20 13:56 UTC, adeliegorce commented on src/pspec_likelihood/likelihood.py
> -            raise ValueError("window_function must be (Nk_obs, Nk_th) matrix")
Already fixed in another PR, need to merge

2023-06-20 15:48 UTC, adeliegorce commented
Hey @steven-murray, thanks for this PR! 
I started writing a quick test for the new feature but realized things were more complicated than we thought. 
I had to make a few changes to the `_discretize` function. Namely, things get complicated for the `quad` integration rule as, if the width along `kperp` or `kpar` is zero, the integral is zero - so I had to add some `if` statements covering this option. Unfortunately, the comparison between the different integration methods in `tests_likelihoods` does not give very good results - we need to figure out what to do about this.

2023-06-21 02:52 UTC, steven-murray commented on src/pspec_likelihood/likelihood.py
> +        vector, computing at (kperp, kpar).
I think we could include this info in the main part of the docstring, not just in the parameter info, because I think it's an important part of how the whole class works. Then you can also use the `:math:` environment to make the math look good. 

One more thing -- not sure "equivalent" is the right word here. It's that it needs to properly approximate performing that integral, under the assumption that the only thing that the window function does is directly multiply the theory at the given k samples.

2023-06-21 02:53 UTC, steven-murray commented
@adeliegorce awesome job! I have only the one comment about documentation.

2023-06-21 13:49 UTC, adeliegorce commented on src/pspec_likelihood/likelihood.py
> +        vector, computing at (kperp, kpar).
OK, changed it!

2023-06-21 15:51 UTC, steven-murray commented on src/pspec_likelihood/likelihood.py
> +        vector, computing at (kperp, kpar).
Great! It has my approval (though you'll have to do the formal approval...)

2023-06-21 16:02 UTC, merged